server:
  port: 9010

spring:
  application:
    name: messages
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-comunication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: comunication-sent
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


